version: "3"
services:
  fastapi:
    build: .
    restart: always
    expose:
      - "80"
    labels:
      - traefik.enable=true
      # Docker내 어플리케이션 서버가 다르다면 포트변경 필요
      - traefik.http.services.app.loadbalancer.server.port=80
      - traefik.http.routers.app-http.entrypoints=http
      # 자신의 Subdomain으로 변경필요
      - traefik.http.routers.app-http.rule=Host(`api.jhnoru.me`)
      - traefik.docker.network=traefik-public
      - traefik.http.routers.app-https.entrypoints=https
      # 자신의 Subdomain으로 변경필요
      - traefik.http.routers.app-https.rule=Host(`api.jhnoru.me`)
      - traefik.http.routers.app-https.tls=true
      - traefik.http.routers.app-https.tls.certresolver=le
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.app-http.middlewares=https-redirect
    networks:
      - traefik-public
networks:
  traefik-public:
    external: true